version: '3'

vars:
  APP_NAME: komikan
  BUILD_DIR: bin
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task -l

  build:
    desc: Build all binaries for current platform
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -ldflags="-X 'main.version={{.VERSION}}'" -o {{.BUILD_DIR}}/{{.APP_NAME}}-cli ./cmd/cli
      - go build -ldflags="-X 'main.version={{.VERSION}}'" -o {{.BUILD_DIR}}/{{.APP_NAME}}-bot ./cmd/bot
    sources:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    generates:
      - "{{.BUILD_DIR}}/{{.APP_NAME}}-cli"
      - "{{.BUILD_DIR}}/{{.APP_NAME}}-bot"

  build-cli:
    desc: Build CLI binary
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -ldflags="-X 'main.version={{.VERSION}}'" -o {{.BUILD_DIR}}/{{.APP_NAME}}-cli ./cmd/cli

  build-bot:
    desc: Build Bot binary
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -ldflags="-X 'main.version={{.VERSION}}'" -o {{.BUILD_DIR}}/{{.APP_NAME}}-bot ./cmd/bot

  build-arm64:
    desc: Build for Raspberry Pi 3 (ARM64)
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - GOOS=linux GOARCH=arm64 go build -ldflags="-X 'main.version={{.VERSION}}'" -o {{.BUILD_DIR}}/{{.APP_NAME}}-cli-arm64 ./cmd/cli
      - GOOS=linux GOARCH=arm64 go build -ldflags="-X 'main.version={{.VERSION}}'" -o {{.BUILD_DIR}}/{{.APP_NAME}}-bot-arm64 ./cmd/bot
      - echo "Built ARM64 binaries for Raspberry Pi"
    generates:
      - "{{.BUILD_DIR}}/{{.APP_NAME}}-cli-arm64"
      - "{{.BUILD_DIR}}/{{.APP_NAME}}-bot-arm64"

  build-armhf:
    desc: Build for Raspberry Pi 3 (ARMv7/ARMHF)
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - GOOS=linux GOARCH=arm GOARM=7 go build -ldflags="-X 'main.version={{.VERSION}}'" -o {{.BUILD_DIR}}/{{.APP_NAME}}-cli-armhf ./cmd/cli
      - GOOS=linux GOARCH=arm GOARM=7 go build -ldflags="-X 'main.version={{.VERSION}}'" -o {{.BUILD_DIR}}/{{.APP_NAME}}-bot-armhf ./cmd/bot
      - echo "Built ARMHF binaries for Raspberry Pi"
    generates:
      - "{{.BUILD_DIR}}/{{.APP_NAME}}-cli-armhf"
      - "{{.BUILD_DIR}}/{{.APP_NAME}}-bot-armhf"

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BUILD_DIR}}
      - rm -rf data/*.db

  run-cli:
    desc: Run CLI
    cmds:
      - go run ./cmd/cli {{.CLI_ARGS}}

  run-bot:
    desc: Run Bot
    cmds:
      - go run ./cmd/bot {{.CLI_ARGS}}

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  lint:
    desc: Run linter
    cmds:
      - staticcheck ./...

  deps:
    desc: Install dependencies
    cmds:
      - go mod download
